---
- hosts: builder
  roles:
    - fetch-packages

- hosts: localhost
  roles:
    - role: publish-rpm-nexus
      remote_repo_path: '{{ nexus.repos.yum_tpc }}/{{ zuul.branch }}/source'
    - role: publish-rpm-artifactory
      remote_repo_path: 'http://svl-artifactory.juniper.net/artifactory/contrail-tpc/{{ zuul.branch }}/source'

- hosts: builder
  roles:
    - role: run-nexus-script
      nexus_task_uuid: '{{ nexus.scripts.yum_tpc.rebuild_metadata }}'
